name: CD - Deploy Backend


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: robinsonir
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root1234
          DOCKER_HUB_USERNAME: robinsonir
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1
      - name: Gradle Build
        run: gradle clean build
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        run: npm install  --prefix src/main/ui
      - name: Build Frontend
        run: npm run build --prefix src/main/ui
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_HUB_USERNAME}}/fitness-tracker:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Publish dockerimage to docker hub
        run: docker push ${{env.DOCKER_HUB_USERNAME}}/fitness-tracker:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_HUB_USERNAME}}/fitness-tracker:latest
      - name: Publish dockerimage to docker hub
        run: docker push ${{env.DOCKER_HUB_USERNAME}}/fitness-tracker:latest