name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  POSTGRESQL_VERSION: 14
  POSTGRESQL_DB: robinsonir
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: root
  JAVA_VERSION: 1.17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Build with Gradle
        run: gradle clean build

      - name: List Library contents
        run: ls

      - name: Change to UI Directory
        run: cd src/main/ui

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install UI Dependencies
        run: npm install  # You can also use "yarn install" if you prefer Yarn.

      - name: Build React UI
        run: npm run build
