name: CD - Deploy Backend


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - frontend/react/**
jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react
    steps:
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build