name: CD - Deploy Frontend


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - frontend/react/**
      - backend/**
jobs:
  deploy:
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.modified, 'frontend/react/')"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react
    steps:
      - uses: actions/checkout@v2
      - name: Check for Changes in Backend
        id: backend-changes
        run: |
          # Check if any files in the backend/ directory have been modified
          if git diff --exit-code --quiet HEAD^ HEAD -- backend/; then
            echo "No changes detected in backend/ directory."
            echo "::set-output name=backend_changed::false"
          else
            echo "Changes detected in backend/ directory."
            echo "::set-output name=backend_changed::true"
          fi
      

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:${{steps.build-number.outputs.BUILD_NUMBER}} \
          --build-arg api_base_url=http://http://robinsonir-api-env.eba-aebgw6jr.us-east-1.elasticbeanstalk.com/8080
      - name: Publish docker image to docker hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Build Docker image with latest tag
        run: |
          docker build . \
          --file Dockerfile \
          --tag ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:latest \
          --build-arg api_base_url=http://fitness-tracker-env.eba-3f5efq3k.us-east-1.elasticbeanstalk.com:8080
      - name: Publish docker image to docker hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:latest
      - name: Wait 1 minute
        if: steps.backend-changes.outputs.backend_changed == 'true'
        run: |
          echo "Waiting 75 seconds"
          sleep 75  # Wait for 75 seconds
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: Dockerrun.aws.json
          wait_for_environment_recovery: 60
